#!/bin/sh
#
# Shared output functions for dotfiles scripts.

info () {
  printf "  [ \033[00;34m..\033[0m ] %s\n" "$1"
}

user () {
  printf "  [ \033[0;33m??\033[0m ] %s " "$1"
}

success () {
  printf "  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

fail () {
  printf "  [\033[0;31mFAIL\033[0m] %s\n" "$1"
  echo ''
  exit 1
}
