#!/bin/bash

# Get the color flag depending on OS
COLOR='--color'
if [ "$(echo $(uname) | tr A-Z a-z)" = "darwin" ]; then
  COLOR='-G'
fi

alias ls="ls ${COLOR}"  # enable colorized listings
alias l.='ls -d .*'     # list hidden files
alias ll.='ls -ld .*'   # long listing of hidden files
alias ll='ls -lh'       # long listing of files
alias la='ls -lha'      # list all files 
alias lA='ls -lhA'      # list all files (including . and ..)
alias lsd='ls -Ud'      # list directories as files
alias lld='ls -lUd'     # long listing of directories as files

alias grep='grep --color'   # enable colorized results
alias egrep='egrep --color' # enable colorized results
alias fgrep='fgrep --color' # enable colorized results
alias pdb='python -m pdb' # add quick alias for python debugger

# Use vim instead of less
if [ ! -z $(which vim) ] && [ -f "${HOME}/.bin/less.sh" ]; then
  alias less="${HOME}/.bin/less.sh"
fi

