#!/bin/bash
# The following code is a modified version of Sam Rowe's solution to using
# SSH-Agent and a terimnal multiplexer which can be found at the following:
# http://www.deadman.org/sshscreen.php

SSHVARS="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

# Dynamically create a function called fixssh()
FUNCTION="fixssh() { "
for x in ${SSHVARS}; 
do
  FUNCTION="${FUNCTION}$((eval echo $x=\"\$$x\") | \
  sed 's/=/="/
       s/$/"/
       s/^/export /'); "
done #1>$HOME/bin/fixssh
FUNCTION="${FUNCTION}}"
eval "${FUNCTION}"

unset FUNCTION SSHVARS
