#!/bin/bash

# Setup generic system path for all systems
PATH="${HOME}/.bin:${PATH}"

# Add any machine specific paths from ${FILE}
FILE="${HOME}/.pathrc"
if [ -f "${FILE}" ]; then
  while read line
  do
    [ -z $line ] && continue
    if [ -z "${TEMP}" ]; then
      eval TEMP=$(eval echo $line)
    else
      eval TEMP="${TEMP}:$(eval echo $line)"
    fi
  done < "${FILE}"
fi

export PATH="${TEMP}:${PATH}"
