#!/bin/bash

# Parse directories from ${FILE} and add to ${VAR}
path_helper() {
  TEMP=
  FILE="$1"
  VAR="$2"
  if [ -f "${FILE}" ]; then
    while read line
    do
      [ -z $line ] && continue
      if [ -z "${TEMP}" ]; then
        TEMP="$(eval echo $line)"
      else
        TEMP="${TEMP}:$(eval echo $line)"
      fi
    done < "${FILE}"
  fi

  if [ ! -z "${TEMP}" ]; then
    VARPATH=$(eval 'echo ${'"${VAR}"'}')
    export "${VAR}"="${TEMP}:${VARPATH}"
  fi
}

path_helper "${HOME}/.bash/paths" "PATH"
path_helper "${HOME}/.pathrc" "PATH"
path_helper "${HOME}/.bash/pythonpaths" "PYTHONPATH"
path_helper "${HOME}/.pythonpathrc" "PYTHONPATH"

unset path_helper

